<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Werkr.Api</RootNamespace>
    <AssemblyName>Werkr.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Werkr.Common\Protos\Registration.proto" GrpcServices="Server" Link="Protos\Registration.proto" />
    <Protobuf Include="..\Werkr.Common\Protos\ScheduleSync.proto" GrpcServices="Server" Link="Protos\ScheduleSync.proto" />
    <Protobuf Include="..\Werkr.Common\Protos\ScheduleInvalidation.proto" GrpcServices="Client" Link="Protos\ScheduleInvalidation.proto" />
    <Protobuf Include="..\Werkr.Common\Protos\JobReport.proto" GrpcServices="Server" Link="Protos\JobReport.proto" />
    <Protobuf Include="..\Werkr.Common\Protos\OutputFetch.proto" GrpcServices="Client" Link="Protos\OutputFetch.proto" />
    <Protobuf Include="..\Werkr.Common\Protos\OutputStreaming.proto" GrpcServices="Server" Link="Protos\OutputStreaming.proto" />
    <Protobuf Include="..\Werkr.Common\Protos\VariableService.proto" GrpcServices="Server" Link="Protos\VariableService.proto" />
    <!-- ConnectionManagement.proto types are generated by Werkr.Core (GrpcServices="Both")
         and imported via ProjectReference. -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Werkr.ServiceDefaults\Werkr.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Werkr.Common\Werkr.Common.csproj" />
    <ProjectReference Include="..\Werkr.Core\Werkr.Core.csproj" />
    <ProjectReference Include="..\Werkr.Data\Werkr.Data.csproj" />
  </ItemGroup>
</Project>
