using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Werkr.Data.Entities.Schedule;

/// <summary>
/// A specific holiday date within a <see cref="HolidayCalendar"/>.
/// May be generated by a <see cref="HolidayRule"/> (materialized cache) or manually entered.
/// </summary>
[Table( "holiday_dates" )]
public class HolidayDate {

    /// <summary>Auto-incrementing primary key.</summary>
    [Key]
    [DatabaseGenerated( DatabaseGeneratedOption.Identity )]
    public long Id { get; set; }

    /// <summary>FK to the owning calendar.</summary>
    public Guid HolidayCalendarId { get; set; }

    /// <summary>FK to the rule that generated this date. Null for manually entered dates.</summary>
    public long? HolidayRuleId { get; set; }

    /// <summary>The holiday date.</summary>
    public DateOnly Date { get; set; }

    /// <summary>Display name for this date (e.g., "Independence Day (Observed)").</summary>
    [Required]
    [MaxLength( 256 )]
    public string Name { get; set; } = string.Empty;

    /// <summary>The year this date applies to.</summary>
    public int Year { get; set; }

    /// <summary>Optional start of time window for partial-day holidays.</summary>
    public TimeOnly? WindowStart { get; set; }

    /// <summary>Optional end of time window for partial-day holidays.</summary>
    public TimeOnly? WindowEnd { get; set; }

    /// <summary>IANA/Windows timezone ID for the time window.</summary>
    [MaxLength( 128 )]
    public string? WindowTimeZoneId { get; set; }

    /// <summary>Whether this date was manually entered (true) or generated by a rule (false). Decision H16.</summary>
    [NotMapped]
    public bool IsManual => HolidayRuleId is null;

    // -- Navigation properties --

    /// <summary>The calendar this date belongs to.</summary>
    public HolidayCalendar Calendar { get; set; } = null!;

    /// <summary>The rule that generated this date, or null for manual entries.</summary>
    public HolidayRule? GeneratedByRule { get; set; }
}
