using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Werkr.Data.Calendar.Enums;

namespace Werkr.Data.Entities.Schedule;

/// <summary>
/// An algorithmic rule that computes holiday dates for a <see cref="HolidayCalendar"/>.
/// </summary>
[Table( "holiday_rules" )]
public class HolidayRule {

    /// <summary>Auto-incrementing primary key.</summary>
    [Key]
    [DatabaseGenerated( DatabaseGeneratedOption.Identity )]
    public long Id { get; set; }

    /// <summary>FK to the owning calendar.</summary>
    public Guid HolidayCalendarId { get; set; }

    /// <summary>Display name (e.g., "New Year's Day").</summary>
    [Required]
    [MaxLength( 256 )]
    public string Name { get; set; } = string.Empty;

    /// <summary>The type of rule (FixedDate, NthWeekdayOfMonth, LastWeekdayOfMonth).</summary>
    public HolidayRuleType RuleType { get; set; }

    /// <summary>Month (1-12). Required for all rule types. Uses int? not the Month enum (Decision H20).</summary>
    public int? Month { get; set; }

    /// <summary>Day of month (1-31). Required for FixedDate rules.</summary>
    public int? Day { get; set; }

    /// <summary>Day of week. Required for NthWeekdayOfMonth and LastWeekdayOfMonth.</summary>
    public DayOfWeek? DayOfWeek { get; set; }

    /// <summary>Week number within the month (1-5). Required for NthWeekdayOfMonth.</summary>
    public int? WeekNumber { get; set; }

    /// <summary>Optional start of time window for partial-day holidays.</summary>
    public TimeOnly? WindowStart { get; set; }

    /// <summary>Optional end of time window for partial-day holidays.</summary>
    public TimeOnly? WindowEnd { get; set; }

    /// <summary>IANA/Windows timezone ID for the time window. Required if WindowStart/WindowEnd are set.</summary>
    [MaxLength( 128 )]
    public string? WindowTimeZoneId { get; set; }

    /// <summary>How the holiday is observed when it falls on a weekend.</summary>
    public ObservanceRule ObservanceRule { get; set; }

    /// <summary>Earliest year this rule applies (inclusive). Null means no lower bound.</summary>
    public int? YearStart { get; set; }

    /// <summary>Latest year this rule applies (inclusive). Null means no upper bound.</summary>
    public int? YearEnd { get; set; }

    // -- Navigation properties --

    /// <summary>The calendar this rule belongs to.</summary>
    public HolidayCalendar Calendar { get; set; } = null!;

    /// <summary>Dates generated by this rule (materialized cache).</summary>
    public ICollection<HolidayDate> GeneratedDates { get; set; } = [];
}
