// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Werkr.Data;

#nullable disable

namespace Werkr.Data.Migrations.Sqlite
{
    [DbContext(typeof(SqliteWerkrDbContext))]
    [Migration("20260312210510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Werkr.Data.Entities.Registration.RegisteredConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActiveKeyId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("active_key_id");

                    b.Property<string>("AllowedPaths")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_paths");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<bool>("EnforceAllowlist")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enforce_allowlist");

                    b.Property<string>("InboundApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("inbound_api_key_hash");

                    b.Property<bool>("IsServer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_server");

                    b.Property<string>("LastSeen")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("LocalPrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_private_key");

                    b.Property<string>("LocalPublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_public_key");

                    b.Property<string>("OutboundApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("outbound_api_key");

                    b.Property<string>("PreviousKeyId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_key_id");

                    b.Property<string>("PreviousSharedKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_shared_key");

                    b.Property<string>("RemotePublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_public_key");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_url");

                    b.Property<string>("SharedKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shared_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_registered_connections");

                    b.HasIndex("ConnectionName")
                        .HasDatabaseName("ix_registered_connections_connection_name");

                    b.HasIndex("RemoteUrl")
                        .HasDatabaseName("ix_registered_connections_remote_url");

                    b.ToTable("registered_connections", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Registration.RegistrationBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AllowedPaths")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_paths");

                    b.Property<string>("BundleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bundle_id");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<int>("KeySize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("key_size");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("ServerPrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("server_private_key");

                    b.Property<string>("ServerPublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("server_public_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_registration_bundles");

                    b.HasIndex("BundleId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_bundles_bundle_id");

                    b.ToTable("registration_bundles", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DailyRecurrence", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<int>("DayInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_interval");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_daily_recurrence");

                    b.ToTable("daily_recurrence", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DbSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("CatchUpEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("catch_up_enabled");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("StopTaskAfterMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stop_task_after_minutes");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ExpirationDateTimeInfo", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_schedule_expiration");

                    b.ToTable("schedule_expiration", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemCalendar")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_calendar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_holiday_calendars");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_holiday_calendars_name");

                    b.ToTable("holiday_calendars", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("TEXT")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<long?>("HolidayRuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("holiday_rule_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_end");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_start");

                    b.Property<string>("WindowTimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("window_time_zone_id");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_holiday_dates");

                    b.HasIndex("HolidayRuleId")
                        .HasDatabaseName("ix_holiday_dates_holiday_rule_id");

                    b.HasIndex("HolidayCalendarId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_holiday_dates_holiday_calendar_id_date");

                    b.ToTable("holiday_dates", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<int?>("Day")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("TEXT")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ObservanceRule")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("observance_rule");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_type");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("week_number");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_end");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_start");

                    b.Property<string>("WindowTimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("window_time_zone_id");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year_end");

                    b.Property<int?>("YearStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year_start");

                    b.HasKey("Id")
                        .HasName("pk_holiday_rules");

                    b.HasIndex("HolidayCalendarId")
                        .HasDatabaseName("ix_holiday_rules_holiday_calendar_id");

                    b.ToTable("holiday_rules", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.MonthlyRecurrence", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("DayNumbers")
                        .HasColumnType("TEXT")
                        .HasColumnName("day_numbers");

                    b.Property<int?>("DaysOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("days_of_week");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<int>("MonthsOfYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("months_of_year");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("week_number");

                    b.HasKey("ScheduleId")
                        .HasName("pk_monthly_recurrence");

                    b.ToTable("monthly_recurrence", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    b.Property<string>("CalendarName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("calendar_name");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("holiday_name");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("OccurrenceUtcTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurrence_utc_time");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_schedule_audit_log");

                    b.HasIndex("ScheduleId", "OccurrenceUtcTime")
                        .HasDatabaseName("ix_schedule_audit_log_schedule_id_occurrence_utc_time");

                    b.ToTable("schedule_audit_log", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleHolidayCalendar", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("TEXT")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.HasKey("ScheduleId", "HolidayCalendarId")
                        .HasName("pk_schedule_holiday_calendars");

                    b.HasIndex("HolidayCalendarId")
                        .HasDatabaseName("ix_schedule_holiday_calendars_holiday_calendar_id");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_holiday_calendars_schedule_id");

                    b.ToTable("schedule_holiday_calendars", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleRepeatOptions", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<int>("RepeatDurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_duration_minutes");

                    b.Property<int>("RepeatIntervalMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_interval_minutes");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_schedule_repeat_options");

                    b.ToTable("schedule_repeat_options", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.StartDateTimeInfo", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_schedule_start_datetimeinfo");

                    b.ToTable("schedule_start_datetimeinfo", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.WeeklyRecurrence", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("days_of_week");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<int>("WeekInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("week_interval");

                    b.HasKey("ScheduleId")
                        .HasName("pk_weekly_recurrence");

                    b.ToTable("weekly_recurrence", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.TaskSchedule", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_one_time");

                    b.HasKey("TaskId", "ScheduleId")
                        .HasName("pk_task_schedules");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_task_schedules_schedule_id");

                    b.ToTable("task_schedules", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentConnectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_connection_id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorCategory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("error_category");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Output")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("output");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_path");

                    b.Property<double>("RuntimeSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("runtime_seconds");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<long?>("StepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_id");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskSnapshot")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("task_snapshot");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("AgentConnectionId")
                        .HasDatabaseName("ix_jobs_agent_connection_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_jobs_schedule_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_jobs_step_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_jobs_task_id");

                    b.HasIndex("WorkflowRunId", "StepId")
                        .HasDatabaseName("IX_jobs_WorkflowRunId_StepId");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionParameters")
                        .HasColumnType("TEXT")
                        .HasColumnName("action_parameters");

                    b.Property<string>("ActionSubType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("action_sub_type");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsEphemeral")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ephemeral");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SuccessCriteria")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("success_criteria");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sync_interval_minutes");

                    b.Property<string>("TargetTags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_tags");

                    b.Property<long?>("TimeoutMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_minutes");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<long?>("WorkflowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_tasks_workflow_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.Workflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TargetTags")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_tags");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_runs");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_runs_workflow_id");

                    b.ToTable("workflow_runs", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRunVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<Guid?>("ProducedByJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("produced_by_job_id");

                    b.Property<long?>("ProducedByStepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produced_by_step_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("variable_name");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_run_variables");

                    b.HasIndex("ProducedByJobId")
                        .HasDatabaseName("ix_workflow_run_variables_produced_by_job_id");

                    b.HasIndex("ProducedByStepId")
                        .HasDatabaseName("ix_workflow_run_variables_produced_by_step_id");

                    b.HasIndex("WorkflowRunId", "VariableName", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_run_variables_workflow_run_id_variable_name_version");

                    b.ToTable("workflow_run_variables", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowSchedule", b =>
                {
                    b.Property<long>("WorkflowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_id");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_one_time");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("WorkflowId", "ScheduleId")
                        .HasName("pk_workflow_schedules");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_workflow_schedules_schedule_id");

                    b.ToTable("workflow_schedules", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentConnectionIdOverride")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_connection_id_override");

                    b.Property<string>("ConditionExpression")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_expression");

                    b.Property<string>("ControlStatement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("control_statement");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("DependencyMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dependency_mode");

                    b.Property<string>("InputVariableName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("input_variable_name");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_iterations");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<string>("OutputVariableName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_variable_name");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_steps");

                    b.HasIndex("AgentConnectionIdOverride")
                        .HasDatabaseName("ix_workflow_steps_agent_connection_id_override");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_workflow_steps_task_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_steps_workflow_id");

                    b.ToTable("workflow_steps", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepDependency", b =>
                {
                    b.Property<long>("StepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_id");

                    b.Property<long>("DependsOnStepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depends_on_step_id");

                    b.HasKey("StepId", "DependsOnStepId")
                        .HasName("pk_workflow_step_dependencies");

                    b.HasIndex("DependsOnStepId")
                        .HasDatabaseName("ix_workflow_step_dependencies_depends_on_step_id");

                    b.ToTable("workflow_step_dependencies", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("skip_reason");

                    b.Property<string>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("StepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_step_executions");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_workflow_step_executions_job_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_workflow_step_executions_step_id");

                    b.HasIndex("WorkflowRunId")
                        .HasDatabaseName("ix_workflow_step_executions_workflow_run_id");

                    b.HasIndex("WorkflowRunId", "StepId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_step_executions_workflow_run_id_step_id_attempt");

                    b.ToTable("workflow_step_executions", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Created")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_variables");

                    b.HasIndex("WorkflowId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_variables_workflow_id_name");

                    b.ToTable("workflow_variables", (string)null);
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DailyRecurrence", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("DailyRecurrence")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.DailyRecurrence", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_recurrence_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ExpirationDateTimeInfo", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("Expiration")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.ExpirationDateTimeInfo", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_expiration_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayDate", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayCalendar", "Calendar")
                        .WithMany("Dates")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_dates_holiday_calendars_holiday_calendar_id");

                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayRule", "GeneratedByRule")
                        .WithMany("GeneratedDates")
                        .HasForeignKey("HolidayRuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_holiday_dates_holiday_rules_holiday_rule_id");

                    b.Navigation("Calendar");

                    b.Navigation("GeneratedByRule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayRule", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayCalendar", "Calendar")
                        .WithMany("Rules")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_rules_holiday_calendars_holiday_calendar_id");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.MonthlyRecurrence", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("MonthlyRecurrence")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.MonthlyRecurrence", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monthly_recurrence_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleAuditLog", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_audit_log_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleHolidayCalendar", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayCalendar", "Calendar")
                        .WithMany("ScheduleLinks")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_holiday_calendars_holiday_calendars_holiday_calendar_id");

                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("HolidayCalendarLink")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.ScheduleHolidayCalendar", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_holiday_calendars_schedules_schedule_id");

                    b.Navigation("Calendar");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleRepeatOptions", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("RepeatOptions")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.ScheduleRepeatOptions", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_repeat_options_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.StartDateTimeInfo", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("StartDateTime")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.StartDateTimeInfo", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_start_datetimeinfo_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.WeeklyRecurrence", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("WeeklyRecurrence")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.WeeklyRecurrence", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_recurrence_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.TaskSchedule", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithMany("TaskSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_schedules_schedules_schedule_id");

                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrTask", "Task")
                        .WithMany("TaskSchedules")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_schedules_tasks_task_id");

                    b.Navigation("Schedule");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrJob", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Registration.RegisteredConnection", "AgentConnection")
                        .WithMany()
                        .HasForeignKey("AgentConnectionId")
                        .HasConstraintName("fk_jobs_registered_connections_agent_connection_id");

                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("fk_jobs_schedules_schedule_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_workflow_steps_step_id");

                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_tasks_task_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowRun", "WorkflowRun")
                        .WithMany("Jobs")
                        .HasForeignKey("WorkflowRunId")
                        .HasConstraintName("fk_jobs_workflow_runs_workflow_run_id");

                    b.Navigation("AgentConnection");

                    b.Navigation("Schedule");

                    b.Navigation("Step");

                    b.Navigation("Task");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrTask", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowId")
                        .HasConstraintName("fk_tasks_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRun", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_runs_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRunVariable", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrJob", "ProducedByJob")
                        .WithMany()
                        .HasForeignKey("ProducedByJobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_run_variables_jobs_produced_by_job_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "ProducedByStep")
                        .WithMany()
                        .HasForeignKey("ProducedByStepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_run_variables_workflow_steps_produced_by_step_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowRun", "WorkflowRun")
                        .WithMany("RunVariables")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_run_variables_workflow_runs_workflow_run_id");

                    b.Navigation("ProducedByJob");

                    b.Navigation("ProducedByStep");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowSchedule", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithMany("WorkflowSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_schedules_schedules_schedule_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("WorkflowSchedules")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_schedules_workflows_workflow_id");

                    b.Navigation("Schedule");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Registration.RegisteredConnection", "AgentConnectionOverride")
                        .WithMany()
                        .HasForeignKey("AgentConnectionIdOverride")
                        .HasConstraintName("fk_workflow_steps_registered_connections_agent_connection_id_override");

                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_steps_tasks_task_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_steps_workflows_workflow_id");

                    b.Navigation("AgentConnectionOverride");

                    b.Navigation("Task");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepDependency", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "DependsOnStep")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_dependencies_workflow_steps_depends_on_step_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "Step")
                        .WithMany("Dependencies")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_dependencies_workflow_steps_step_id");

                    b.Navigation("DependsOnStep");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepExecution", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_step_executions_jobs_job_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_executions_workflow_steps_step_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowRun", "WorkflowRun")
                        .WithMany("StepExecutions")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_executions_workflow_runs_workflow_run_id");

                    b.Navigation("Job");

                    b.Navigation("Step");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowVariable", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Variables")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_variables_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DbSchedule", b =>
                {
                    b.Navigation("DailyRecurrence");

                    b.Navigation("Expiration");

                    b.Navigation("HolidayCalendarLink");

                    b.Navigation("MonthlyRecurrence");

                    b.Navigation("RepeatOptions");

                    b.Navigation("StartDateTime");

                    b.Navigation("TaskSchedules");

                    b.Navigation("WeeklyRecurrence");

                    b.Navigation("WorkflowSchedules");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayCalendar", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Rules");

                    b.Navigation("ScheduleLinks");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayRule", b =>
                {
                    b.Navigation("GeneratedDates");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrTask", b =>
                {
                    b.Navigation("TaskSchedules");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.Workflow", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Steps");

                    b.Navigation("Tasks");

                    b.Navigation("Variables");

                    b.Navigation("WorkflowSchedules");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRun", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("RunVariables");

                    b.Navigation("StepExecutions");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
