name: Contribution License Agreement
description: Read and agree to the [Contribution License Agreement](https://docs.werkr.app/ContributionLicenseAgreement.html).
title: "[CLA]: {GITHUB USERNAME}"
labels: ["cla"]
assignees:
  - tsmarvin
body:
  - type: markdown
    attributes:
      value: Thanks for contributing!
  - type: checkboxes
    id: agreementstatement
    attributes:
      label: Terms
      description: |
        Please select one of the two checkbox options below and fill out the rest of the form as indicated.
        By signing, You accept and agree to the terms of this [Contribution License Agreement](https://docs.werkr.app/ContributionLicenseAgreement.html) for Your present and future Submissions to Darkgrey Development.
      options:
        - label: I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
        - label: I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law).  I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer.  By signing below, the defined term "You" includes me and my employer.
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Name ("You")
      description: Please enter your legal name.
    validations:
      required: true
  - type: input
    id: signature
    attributes:
      label: Signature
      description: Sign your name.
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      description: Enter the date in "yyyy-MM-dd" format.
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: GitHub	Login
      description: Enter your github username.
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      description: Enter your email contact information.
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: Address
      description: Enter your legal address.
    validations:
      required: true
  - type: input
    id: companyname
    attributes:
      label: Company Name
      description: Employer agreement only - Enter your companys legal name (and dba if applicable).
  - type: input
    id: title
    attributes:
      label: Title
      description: Employer agreement only - Enter your business title.
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://docs.werkr.app/CODE_OF_CONDUCT.html).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    id: license
    attributes:
      label: LICENSE AGREEMENT & ISSUE SUBMISSION TERMS
      description: |
        By submitting this issue, I have read and agree to abide by the softwares [MIT LICENSE](https://docs.werkr.app/LICENSE.html) agreement.
        I understand there is no warranty of any kind, express or implied. I further understand that any and all support is offered on a volunteer and community basis.
        Any advice or suggestion I chose to follow is an action I take at my own risk.
      options:
        - label: By submitting this issue, I agree to abide by the softwares license agreement and understand the issue submission terms.
          required: true
