blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.werkr.app
    about: Review [How-To](https://docs.werkr.app/articles/HowTo/index.html) articles and [api](https://docs.werkr.app/api/index.html) documentation.
  - name: Community Discussions
    url: https://github.com/DarkgreyDevelopment/Werkr.App/discussions
    about: Please ask and answer questions here! Welcome to the community!
