namespace Werkr.Common.Models.Holidays;

/// <summary>Response containing the materialised dates generated by a previewed holiday rule.</summary>
public sealed record RulePreviewResponse(
    int StartYear,
    int EndYear,
    IReadOnlyList<HolidayDateDto> Dates
);
