// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Werkr.Data;

#nullable disable

namespace Werkr.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresWerkrDbContext))]
    partial class PostgresWerkrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("werkr")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Werkr.Data.Entities.Audit.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionPerformed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_performed");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventCategory")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_category");

                    b.Property<string>("EventTypeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_module");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_events_actor_id");

                    b.HasIndex("EventCategory")
                        .HasDatabaseName("ix_audit_events_event_category");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_audit_events_event_type_id");

                    b.HasIndex("TimestampUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_events_timestamp_utc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_events_entity_type_entity_id");

                    b.ToTable("audit_events", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Registration.RegisteredConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveKeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("active_key_id");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_version");

                    b.Property<string>("AllowedPaths")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_paths");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("connection_name");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("EnforceAllowlist")
                        .HasColumnType("boolean")
                        .HasColumnName("enforce_allowlist");

                    b.Property<string>("InboundApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("inbound_api_key_hash");

                    b.Property<bool>("IsServer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_server");

                    b.Property<DateTime?>("KeyRotatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("key_rotated_at_utc");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("LocalPrivateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local_private_key");

                    b.Property<string>("LocalPublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local_public_key");

                    b.Property<string>("OutboundApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("outbound_api_key");

                    b.Property<string>("PreviousKeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("previous_key_id");

                    b.Property<string>("PreviousSharedKey")
                        .HasColumnType("text")
                        .HasColumnName("previous_shared_key");

                    b.Property<string>("RemotePublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_public_key");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("remote_url");

                    b.Property<string>("SharedKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shared_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_registered_connections");

                    b.HasIndex("ConnectionName")
                        .HasDatabaseName("ix_registered_connections_connection_name");

                    b.HasIndex("RemoteUrl")
                        .HasDatabaseName("ix_registered_connections_remote_url");

                    b.ToTable("registered_connections", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Registration.RegistrationBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedPaths")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_paths");

                    b.Property<string>("BundleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bundle_id");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("connection_name");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("KeySize")
                        .HasColumnType("integer")
                        .HasColumnName("key_size");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("ServerPrivateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_private_key");

                    b.Property<string>("ServerPublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_public_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_registration_bundles");

                    b.HasIndex("BundleId")
                        .IsUnique()
                        .HasDatabaseName("ix_registration_bundles_bundle_id");

                    b.ToTable("registration_bundles", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DailyRecurrence", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int>("DayInterval")
                        .HasColumnType("integer")
                        .HasColumnName("day_interval");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_daily_recurrence");

                    b.ToTable("daily_recurrence", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DbSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CatchUpEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("catch_up_enabled");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("ShiftMode")
                        .HasColumnType("integer")
                        .HasColumnName("shift_mode");

                    b.Property<long>("StopTaskAfterMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("stop_task_after_minutes");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.ToTable("schedules", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ExpirationDateTimeInfo", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_schedule_expiration");

                    b.ToTable("schedule_expiration", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemCalendar")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_calendar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer")
                        .HasColumnName("working_days");

                    b.HasKey("Id")
                        .HasName("pk_holiday_calendars");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_holiday_calendars_name");

                    b.ToTable("holiday_calendars", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<long?>("HolidayRuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("holiday_rule_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_end");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_start");

                    b.Property<string>("WindowTimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("window_time_zone_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_holiday_dates");

                    b.HasIndex("HolidayRuleId")
                        .HasDatabaseName("ix_holiday_dates_holiday_rule_id");

                    b.HasIndex("HolidayCalendarId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_holiday_dates_holiday_calendar_id_date");

                    b.ToTable("holiday_dates", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int?>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<int?>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("ObservanceRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observance_rule");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_type");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.Property<TimeOnly?>("WindowEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_end");

                    b.Property<TimeOnly?>("WindowStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("window_start");

                    b.Property<string>("WindowTimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("window_time_zone_id");

                    b.Property<int?>("YearEnd")
                        .HasColumnType("integer")
                        .HasColumnName("year_end");

                    b.Property<int?>("YearStart")
                        .HasColumnType("integer")
                        .HasColumnName("year_start");

                    b.HasKey("Id")
                        .HasName("pk_holiday_rules");

                    b.HasIndex("HolidayCalendarId")
                        .HasDatabaseName("ix_holiday_rules_holiday_calendar_id");

                    b.ToTable("holiday_rules", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.MonthlyRecurrence", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("DayNumbers")
                        .HasColumnType("text")
                        .HasColumnName("day_numbers");

                    b.Property<int?>("DaysOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("MonthsOfYear")
                        .HasColumnType("integer")
                        .HasColumnName("months_of_year");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.HasKey("ScheduleId")
                        .HasName("pk_monthly_recurrence");

                    b.ToTable("monthly_recurrence", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleHolidayCalendar", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("HolidayCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("holiday_calendar_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.HasKey("ScheduleId", "HolidayCalendarId")
                        .HasName("pk_schedule_holiday_calendars");

                    b.HasIndex("HolidayCalendarId")
                        .HasDatabaseName("ix_schedule_holiday_calendars_holiday_calendar_id");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_holiday_calendars_schedule_id");

                    b.ToTable("schedule_holiday_calendars", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleRepeatOptions", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("RepeatDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_duration_minutes");

                    b.Property<int>("RepeatIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_interval_minutes");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_schedule_repeat_options");

                    b.ToTable("schedule_repeat_options", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.StartDateTimeInfo", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("ScheduleId")
                        .HasName("pk_schedule_start_datetimeinfo");

                    b.ToTable("schedule_start_datetimeinfo", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.WeeklyRecurrence", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("WeekInterval")
                        .HasColumnType("integer")
                        .HasColumnName("week_interval");

                    b.HasKey("ScheduleId")
                        .HasName("pk_weekly_recurrence");

                    b.ToTable("weekly_recurrence", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Settings.SavedFilter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("criteria_json");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("owner_id");

                    b.Property<string>("PageKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("page_key");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_saved_filters");

                    b.HasIndex("PageKey", "IsShared")
                        .HasDatabaseName("ix_saved_filters_page_key_is_shared");

                    b.HasIndex("PageKey", "OwnerId")
                        .HasDatabaseName("ix_saved_filters_page_key_owner_id");

                    b.ToTable("saved_filters", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.TaskSchedule", b =>
                {
                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_one_time");

                    b.HasKey("TaskId", "ScheduleId")
                        .HasName("pk_task_schedules");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_task_schedules_schedule_id");

                    b.ToTable("task_schedules", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.TaskVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_task_versions");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_versions_task_id");

                    b.HasIndex("TaskId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_task_versions_task_id_version_number");

                    b.ToTable("task_versions", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_connection_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_category");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Output")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("output");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("output_path");

                    b.Property<double>("RuntimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("runtime_seconds");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<long?>("StepId")
                        .HasColumnType("bigint")
                        .HasColumnName("step_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskSnapshot")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("task_snapshot");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("AgentConnectionId")
                        .HasDatabaseName("ix_jobs_agent_connection_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_jobs_schedule_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_jobs_step_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_jobs_task_id");

                    b.HasIndex("WorkflowRunId", "StepId")
                        .HasDatabaseName("IX_jobs_WorkflowRunId_StepId");

                    b.ToTable("jobs", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionParameters")
                        .HasColumnType("text")
                        .HasColumnName("action_parameters");

                    b.Property<string>("ActionSubType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_sub_type");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<string>("Arguments")
                        .HasColumnType("text")
                        .HasColumnName("arguments");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<long?>("CurrentVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsEphemeral")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ephemeral");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("SuccessCriteria")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("success_criteria");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sync_interval_minutes");

                    b.Property<string>("TargetTags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_tags");

                    b.Property<long?>("TimeoutMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("timeout_minutes");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<long?>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_tasks_current_version_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_tasks_workflow_id");

                    b.ToTable("tasks", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Triggers.FileMonitorTrigger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CurrentVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_version_id");

                    b.Property<int>("DebounceMs")
                        .HasColumnType("integer")
                        .HasColumnName("debounce_ms");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_types");

                    b.Property<string>("FilePattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_pattern");

                    b.Property<long?>("PinnedWorkflowVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("pinned_workflow_version_id");

                    b.Property<string>("TargetTags")
                        .HasColumnType("text")
                        .HasColumnName("target_tags");

                    b.Property<string>("VersionBindingMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_binding_mode");

                    b.Property<string>("WatchDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("watch_directory");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_file_monitor_triggers");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_file_monitor_triggers_current_version_id");

                    b.HasIndex("PinnedWorkflowVersionId")
                        .HasDatabaseName("ix_file_monitor_triggers_pinned_workflow_version_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_file_monitor_triggers_workflow_id");

                    b.ToTable("file_monitor_triggers", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Triggers.TriggerVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<long>("TriggerId")
                        .HasColumnType("bigint")
                        .HasColumnName("trigger_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_trigger_versions");

                    b.HasIndex("TriggerId")
                        .HasDatabaseName("ix_trigger_versions_trigger_id");

                    b.HasIndex("TriggerId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_trigger_versions_trigger_id_version_number");

                    b.ToTable("trigger_versions", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.Workflow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Annotations")
                        .HasColumnType("text")
                        .HasColumnName("annotations");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<long?>("CurrentVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<bool>("IsChildWorkflow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_child_workflow");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentStepId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_step_id");

                    b.Property<string>("TargetTags")
                        .HasColumnType("text")
                        .HasColumnName("target_tags");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_workflows_current_version_id");

                    b.HasIndex("ParentStepId")
                        .HasDatabaseName("ix_workflows_parent_step_id");

                    b.ToTable("workflows", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.Property<string>("WorkflowNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("workflow_name_snapshot");

                    b.Property<long?>("WorkflowVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_version_id");

                    b.Property<int?>("WorkflowVersionSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_version_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_workflow_runs");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_runs_workflow_id");

                    b.HasIndex("WorkflowVersionId")
                        .HasDatabaseName("ix_workflow_runs_workflow_version_id");

                    b.ToTable("workflow_runs", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRunVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid?>("ProducedByJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("produced_by_job_id");

                    b.Property<long?>("ProducedByStepId")
                        .HasColumnType("bigint")
                        .HasColumnName("produced_by_step_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("variable_name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_run_variables");

                    b.HasIndex("ProducedByJobId")
                        .HasDatabaseName("ix_workflow_run_variables_produced_by_job_id");

                    b.HasIndex("ProducedByStepId")
                        .HasDatabaseName("ix_workflow_run_variables_produced_by_step_id");

                    b.HasIndex("WorkflowRunId", "VariableName", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_run_variables_workflow_run_id_variable_name_version");

                    b.ToTable("workflow_run_variables", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowSchedule", b =>
                {
                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("boolean")
                        .HasColumnName("is_one_time");

                    b.Property<Guid?>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("WorkflowId", "ScheduleId")
                        .HasName("pk_workflow_schedules");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_workflow_schedules_schedule_id");

                    b.ToTable("workflow_schedules", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AgentConnectionIdOverride")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_connection_id_override");

                    b.Property<long?>("ChildWorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("child_workflow_id");

                    b.Property<string>("CollectionVariableName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("collection_variable_name");

                    b.Property<string>("CompositeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("composite_type");

                    b.Property<string>("ConditionExpression")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("condition_expression");

                    b.Property<string>("ControlStatement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("control_statement");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("DependencyMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dependency_mode");

                    b.Property<string>("InputVariableName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("input_variable_name");

                    b.Property<bool>("IsComposite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_composite");

                    b.Property<string>("IterationVariableName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("iteration_variable_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("integer")
                        .HasColumnName("max_iterations");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("OutputVariableName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("output_variable_name");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long?>("TaskVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_version_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_steps");

                    b.HasIndex("AgentConnectionIdOverride")
                        .HasDatabaseName("ix_workflow_steps_agent_connection_id_override");

                    b.HasIndex("ChildWorkflowId")
                        .HasDatabaseName("ix_workflow_steps_child_workflow_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_workflow_steps_task_id");

                    b.HasIndex("TaskVersionId")
                        .HasDatabaseName("ix_workflow_steps_task_version_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_steps_workflow_id");

                    b.ToTable("workflow_steps", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepDependency", b =>
                {
                    b.Property<long>("StepId")
                        .HasColumnType("bigint")
                        .HasColumnName("step_id");

                    b.Property<long>("DependsOnStepId")
                        .HasColumnType("bigint")
                        .HasColumnName("depends_on_step_id");

                    b.HasKey("StepId", "DependsOnStepId")
                        .HasName("pk_workflow_step_dependencies");

                    b.HasIndex("DependsOnStepId")
                        .HasDatabaseName("ix_workflow_step_dependencies_depends_on_step_id");

                    b.ToTable("workflow_step_dependencies", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("skip_reason");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("StepId")
                        .HasColumnType("bigint")
                        .HasColumnName("step_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_step_executions");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_workflow_step_executions_job_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_workflow_step_executions_step_id");

                    b.HasIndex("WorkflowRunId")
                        .HasDatabaseName("ix_workflow_step_executions_workflow_run_id");

                    b.HasIndex("WorkflowRunId", "StepId", "Attempt")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_step_executions_workflow_run_id_step_id_attempt");

                    b.ToTable("workflow_step_executions", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("DataType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<bool>("LogRedaction")
                        .HasColumnType("boolean")
                        .HasColumnName("log_redaction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_variables");

                    b.HasIndex("WorkflowId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_variables_workflow_id_name");

                    b.ToTable("workflow_variables", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<long>("WorkflowId")
                        .HasColumnType("bigint")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_versions");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_workflow_versions_workflow_id");

                    b.HasIndex("WorkflowId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_id_version_number");

                    b.ToTable("workflow_versions", "werkr");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DailyRecurrence", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("DailyRecurrence")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.DailyRecurrence", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_recurrence_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ExpirationDateTimeInfo", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("Expiration")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.ExpirationDateTimeInfo", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_expiration_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayDate", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayCalendar", "Calendar")
                        .WithMany("Dates")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_dates_holiday_calendars_holiday_calendar_id");

                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayRule", "GeneratedByRule")
                        .WithMany("GeneratedDates")
                        .HasForeignKey("HolidayRuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_holiday_dates_holiday_rules_holiday_rule_id");

                    b.Navigation("Calendar");

                    b.Navigation("GeneratedByRule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayRule", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayCalendar", "Calendar")
                        .WithMany("Rules")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_holiday_rules_holiday_calendars_holiday_calendar_id");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.MonthlyRecurrence", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("MonthlyRecurrence")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.MonthlyRecurrence", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monthly_recurrence_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleHolidayCalendar", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.HolidayCalendar", "Calendar")
                        .WithMany("ScheduleLinks")
                        .HasForeignKey("HolidayCalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_holiday_calendars_holiday_calendars_holiday_calend");

                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("HolidayCalendarLink")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.ScheduleHolidayCalendar", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_holiday_calendars_schedules_schedule_id");

                    b.Navigation("Calendar");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.ScheduleRepeatOptions", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("RepeatOptions")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.ScheduleRepeatOptions", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_repeat_options_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.StartDateTimeInfo", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("StartDateTime")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.StartDateTimeInfo", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_start_datetimeinfo_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.WeeklyRecurrence", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithOne("WeeklyRecurrence")
                        .HasForeignKey("Werkr.Data.Entities.Schedule.WeeklyRecurrence", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_recurrence_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.TaskSchedule", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithMany("TaskSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_schedules_schedules_schedule_id");

                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrTask", "Task")
                        .WithMany("TaskSchedules")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_schedules_tasks_task_id");

                    b.Navigation("Schedule");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.TaskVersion", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrTask", "Task")
                        .WithMany("Versions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_versions_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrJob", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Registration.RegisteredConnection", "AgentConnection")
                        .WithMany()
                        .HasForeignKey("AgentConnectionId")
                        .HasConstraintName("fk_jobs_registered_connections_agent_connection_id");

                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("fk_jobs_schedules_schedule_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_workflow_steps_step_id");

                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobs_tasks_task_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowRun", "WorkflowRun")
                        .WithMany("Jobs")
                        .HasForeignKey("WorkflowRunId")
                        .HasConstraintName("fk_jobs_workflow_runs_workflow_run_id");

                    b.Navigation("AgentConnection");

                    b.Navigation("Schedule");

                    b.Navigation("Step");

                    b.Navigation("Task");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrTask", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Tasks.TaskVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_task_versions_current_version_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowId")
                        .HasConstraintName("fk_tasks_workflows_workflow_id");

                    b.Navigation("CurrentVersion");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Triggers.FileMonitorTrigger", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Triggers.TriggerVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_file_monitor_triggers_trigger_versions_current_version_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowVersion", "PinnedWorkflowVersion")
                        .WithMany()
                        .HasForeignKey("PinnedWorkflowVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_file_monitor_triggers_workflow_versions_pinned_workflow_ver");

                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_monitor_triggers_workflows_workflow_id");

                    b.Navigation("CurrentVersion");

                    b.Navigation("PinnedWorkflowVersion");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Triggers.TriggerVersion", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Triggers.FileMonitorTrigger", "Trigger")
                        .WithMany("Versions")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trigger_versions_file_monitor_triggers_trigger_id");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.Workflow", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflows_workflow_versions_current_version_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", null)
                        .WithMany()
                        .HasForeignKey("ParentStepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflows_workflow_steps_parent_step_id");

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRun", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_runs_workflows_workflow_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowVersion", "WorkflowVersion")
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_runs_workflow_versions_workflow_version_id");

                    b.Navigation("Workflow");

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRunVariable", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrJob", "ProducedByJob")
                        .WithMany()
                        .HasForeignKey("ProducedByJobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_run_variables_jobs_produced_by_job_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "ProducedByStep")
                        .WithMany()
                        .HasForeignKey("ProducedByStepId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_run_variables_workflow_steps_produced_by_step_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowRun", "WorkflowRun")
                        .WithMany("RunVariables")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_run_variables_workflow_runs_workflow_run_id");

                    b.Navigation("ProducedByJob");

                    b.Navigation("ProducedByStep");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowSchedule", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Schedule.DbSchedule", "Schedule")
                        .WithMany("WorkflowSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_schedules_schedules_schedule_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("WorkflowSchedules")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_schedules_workflows_workflow_id");

                    b.Navigation("Schedule");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Registration.RegisteredConnection", "AgentConnectionOverride")
                        .WithMany()
                        .HasForeignKey("AgentConnectionIdOverride")
                        .HasConstraintName("fk_workflow_steps_registered_connections_agent_connection_id_o");

                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "ChildWorkflow")
                        .WithMany()
                        .HasForeignKey("ChildWorkflowId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_steps_workflows_child_workflow_id");

                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .HasConstraintName("fk_workflow_steps_tasks_task_id");

                    b.HasOne("Werkr.Data.Entities.Tasks.TaskVersion", "TaskVersion")
                        .WithMany()
                        .HasForeignKey("TaskVersionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_steps_task_versions_task_version_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_steps_workflows_workflow_id");

                    b.Navigation("AgentConnectionOverride");

                    b.Navigation("ChildWorkflow");

                    b.Navigation("Task");

                    b.Navigation("TaskVersion");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepDependency", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "DependsOnStep")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_dependencies_workflow_steps_depends_on_step_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "Step")
                        .WithMany("Dependencies")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_dependencies_workflow_steps_step_id");

                    b.Navigation("DependsOnStep");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStepExecution", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Tasks.WerkrJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workflow_step_executions_jobs_job_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_executions_workflow_steps_step_id");

                    b.HasOne("Werkr.Data.Entities.Workflows.WorkflowRun", "WorkflowRun")
                        .WithMany("StepExecutions")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_executions_workflow_runs_workflow_run_id");

                    b.Navigation("Job");

                    b.Navigation("Step");

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowVariable", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Variables")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_variables_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowVersion", b =>
                {
                    b.HasOne("Werkr.Data.Entities.Workflows.Workflow", "Workflow")
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_versions_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.DbSchedule", b =>
                {
                    b.Navigation("DailyRecurrence");

                    b.Navigation("Expiration");

                    b.Navigation("HolidayCalendarLink");

                    b.Navigation("MonthlyRecurrence");

                    b.Navigation("RepeatOptions");

                    b.Navigation("StartDateTime");

                    b.Navigation("TaskSchedules");

                    b.Navigation("WeeklyRecurrence");

                    b.Navigation("WorkflowSchedules");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayCalendar", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Rules");

                    b.Navigation("ScheduleLinks");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Schedule.HolidayRule", b =>
                {
                    b.Navigation("GeneratedDates");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Tasks.WerkrTask", b =>
                {
                    b.Navigation("TaskSchedules");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Triggers.FileMonitorTrigger", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.Workflow", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("Steps");

                    b.Navigation("Tasks");

                    b.Navigation("Variables");

                    b.Navigation("Versions");

                    b.Navigation("WorkflowSchedules");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowRun", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("RunVariables");

                    b.Navigation("StepExecutions");
                });

            modelBuilder.Entity("Werkr.Data.Entities.Workflows.WorkflowStep", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
