<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Werkr.Common</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="TimeZoneNames" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\EncryptedEnvelope.proto" GrpcServices="None" />
    <Protobuf Include="Protos\GrpcLogMsg.proto" GrpcServices="None" />
    <Protobuf Include="Protos\ResponseMetadata.proto" GrpcServices="None" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Werkr.Common.Configuration\Werkr.Common.Configuration.csproj">
      <TreatAsUsed>true</TreatAsUsed>
    </ProjectReference>
  </ItemGroup>

</Project>
