using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography;

using Werkr.Common.Models;
using Werkr.Data.Entities.Interfaces;

namespace Werkr.Data.Entities.Registration;

/// <summary>
/// Represents an established trust relationship between a Server and an Agent.
/// Both sides persist a <see cref="RegisteredConnection"/> after a successful registration handshake.
/// Each side stores its own RSA key pair, the remote party's RSA public key,
/// a pre-shared AES-256 symmetric key, and an API key (Server stores hash, Agent stores raw).
/// </summary>
[Table( "registered_connections" )]
public class RegisteredConnection : ConcurrencyBase, IKey<Guid> {
    /// <summary>Unique identifier. Also serves as the connection ID in all post-registration communication.</summary>
    [Key]
    [DatabaseGenerated( DatabaseGeneratedOption.Identity )]
    public Guid Id { get; set; }

    /// <summary>Human-readable label for this connection, max 256 characters.</summary>
    [Required]
    [MaxLength( 256 )]
    public string ConnectionName { get; set; } = string.Empty;

    /// <summary>The other party's gRPC endpoint URL, max 2048 characters.</summary>
    [Required]
    [MaxLength( 2048 )]
    public string RemoteUrl { get; set; } = string.Empty;

    /// <summary>Our RSA public key parameters.</summary>
    public RSAParameters LocalPublicKey { get; set; }

    /// <summary>Our RSA private key parameters.</summary>
    public RSAParameters LocalPrivateKey { get; set; }

    /// <summary>The remote party's RSA public key parameters.</summary>
    public RSAParameters RemotePublicKey { get; set; }

    /// <summary>
    /// API key for calling the remote party (outbound bearer token), max 512 characters.
    /// Agent stores the raw Agent→Server key; Server stores the raw Server→Agent key.
    /// Protected at rest by SQLCipher (Agent) or database-level security (Server Postgres).
    /// </summary>
    [MaxLength( 512 )]
    public string OutboundApiKey { get; set; } = string.Empty;

    /// <summary>
    /// SHA-3-512 hash of the API key the remote party uses to call us (inbound validation), max 512 characters.
    /// Server stores hash of Agent→Server key; Agent stores hash of Server→Agent key.
    /// </summary>
    [MaxLength( 512 )]
    public string InboundApiKeyHash { get; set; } = string.Empty;

    /// <summary>
    /// 32-byte AES-256 symmetric key for ongoing message payload encryption.
    /// Generated by Server during registration, delivered to Agent via hybrid encryption.
    /// </summary>
    [Required]
    public byte[] SharedKey { get; set; } = [];

    /// <summary>
    /// Previous shared key retained after a <c>RotateSharedKey</c> RPC so that in-flight
    /// messages encrypted with the old key can still be decrypted during the transition window.
    /// Null when no rotation has occurred or the previous key has been cleared.
    /// </summary>
    public byte[]? PreviousSharedKey { get; set; }

    /// <summary>
    /// Opaque identifier for <see cref="SharedKey"/>, placed in the <c>key_id</c> field of
    /// every <see cref="Common.Protos.EncryptedEnvelope"/>. Defaults to
    /// <see cref="Id"/>.ToString() when null (pre-rotation connections).
    /// </summary>
    [MaxLength( 128 )]
    public string? ActiveKeyId { get; set; }

    /// <summary>
    /// Opaque identifier for <see cref="PreviousSharedKey"/>.
    /// Used to match incoming envelopes that were encrypted before the most recent rotation.
    /// </summary>
    [MaxLength( 128 )]
    public string? PreviousKeyId { get; set; }

    /// <summary>True if this side is the Server in the relationship; false if Agent.</summary>
    public bool IsServer { get; set; }

    /// <summary>Current status of this connection.</summary>
    public ConnectionStatus Status { get; set; } = ConnectionStatus.Connected;

    /// <summary>Timestamp of last successful communication with the remote party (UTC). Null if never communicated.</summary>
    public DateTime? LastSeen { get; set; }

    /// <summary>
    /// Tags assigned to this agent for task targeting. Tasks specify <c>TargetTags</c>
    /// and agents are matched via case-insensitive tag intersection.
    /// </summary>
    public string[] Tags { get; set; } = [];

    /// <summary>
    /// Allowed filesystem path prefixes for built-in action operations.
    /// When <see cref="EnforceAllowlist"/> is <c>true</c>, all file/process action
    /// handler paths are validated against these prefixes on the Agent before execution.
    /// Stored as a JSON column, following the same pattern as <see cref="Tags"/>.
    /// </summary>
    public string[] AllowedPaths { get; set; } = [];

    /// <summary>
    /// When <c>true</c>, the Agent enforces <see cref="AllowedPaths"/> restrictions
    /// on all built-in action handlers. Default <c>false</c> preserves backward compatibility.
    /// </summary>
    public bool EnforceAllowlist { get; set; }
}
