name: DocFX - Documentation Process
on:
  push:
    branches:
      - main
jobs:
  document:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOCFX_SOURCE_BRANCH_NAME: ${{ github.ref }}
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check out Werkr.Agent
        uses: actions/checkout@v2
        with:
          repository: DarkgreyDevelopment/Werkr.Agent
          path: src/Werkr.Agent
          token: ${{ secrets.CI_TOKEN }}
      - name: Check out Werkr.Common
        uses: actions/checkout@v2
        with:
          repository: DarkgreyDevelopment/Werkr.Common
          path: src/Werkr.Common
          token: ${{ secrets.CI_TOKEN }}
      - name: Check out Werkr.Common.Configuration
        uses: actions/checkout@v2
        with:
          repository: DarkgreyDevelopment/Werkr.Common.Configuration
          path: src/Werkr.Common.Configuration
          token: ${{ secrets.CI_TOKEN }}
      - name: Check out Werkr.Installers
        uses: actions/checkout@v2
        with:
          repository: DarkgreyDevelopment/Werkr.Installers
          path: src/Werkr.Installers
          token: ${{ secrets.CI_TOKEN }}
      - name: Check out Werkr.Server
        uses: actions/checkout@v2
        with:
          repository: DarkgreyDevelopment/Werkr.Server
          path: src/Werkr.Server
          token: ${{ secrets.CI_TOKEN }}
      - name: Get DocFX
        shell: pwsh
        run: |
          $IWRParams = @{
            Uri     = "https://github.com/dotnet/docfx/releases/download/v2.59.4/docfx.zip"
            OutFile = '${{ github.workspace }}/docfx.zip'
            Method  = 'Get'
          }
          Invoke-WebRequest @IWRParams
          Expand-Archive -Path '${{ github.workspace }}/docfx.zip' -DestinationPath '${{ github.workspace }}/docfx'
      - name: Custom File processing.
        shell: pwsh
        run: |
          $DocsPath = '${{ github.workspace }}/docs'
          $CopyParams = @{
            Verbose     = $true
            Force       = $true
          }
          copy-item -Path '${{ github.workspace }}/LICENSE' -Destination "$DocsPath/" @CopyParams
          copy-item -Path '${{ github.workspace }}/README.md' -Destination "$DocsPath/index.md" @CopyParams
          copy-item -Path '${{ github.workspace }}/WerkrLogoWithText.png' -Destination "$DocsPath/" @CopyParams
          copy-item -Path '${{ github.workspace }}/Pre-Edit-High-Level-Design-Flow.md' -Destination "$DocsPath/" @CopyParams
          copy-item -Path '${{ github.workspace }}/FeatureList.md' -Destination "$DocsPath/" @CopyParams
      - name: Generate Documentation and build site.
        shell: pwsh
        run: |
          Write-Host "`nGenerating API documentation:"
          & '${{ github.workspace }}/docfx/docfx.exe' metadata '${{ github.workspace }}/docs/docfx.json'
          Write-Host "`nCreating docfx site:"
          & '${{ github.workspace }}/docfx/docfx.exe' '${{ github.workspace }}/docs/docfx.json'
          $CopyToSiteParams = @{
            Destination = '${{ github.workspace }}/docs/_site'
            Verbose     = $true
          }
          copy-item -Path '${{ github.workspace }}/docs/CNAME' @CopyToSiteParams
          copy-item -Path '${{ github.workspace }}/docs/_config.yml' @CopyToSiteParams
          Write-Host "`nCompressing Site for Artifact Upload"
          Compress-Archive -Path '${{ github.workspace }}/docs/_site' -DestinationPath '${{ github.workspace }}/docs/_site.zip'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: ${{ github.workspace }}/docs/_site.zip
  publish:
    needs: document
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOCFX_SOURCE_BRANCH_NAME: ${{ github.ref }}
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
          path: ${{ github.workspace }}/download
      - name: Verify WorkSpace Contents
        shell: pwsh
        run: |
          Write-Host "`Extracting Site."
          Expand-Archive -Path '${{ github.workspace }}/download/_site.zip' -DestinationPath '${{ github.workspace }}/_site'
      - name: Publish Site Content
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: ${{ github.workspace }}/_site
